x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])
print(x + y)     
print(x - y)     
print(x * y)     
print(x / y)     
print(x ** 2)   
print(x.sum())    
print(x.mean())   
print(x.max(), x.min())
print(x.std())    

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(np.dot(m1, m2))     
print(m1.T)              
